### ISSUE TITLE
set_user_by_token not defined in production for rails 5

### ISSUE THREAD

**Issue by djsegal** [lynndylanhurley/devise_token_auth#500]
***note:*** *using a rails 5 api*

for my `production` environment, when `config.eager_load = true`, i'm getting this error:

```
Unable to load application: 
  ArgumentError: Before process_action callback :set_user_by_token has not been defined
```

**Comment by jeryRazakarison** [comment]
Yes, same for me.
The exception is raised at `devise_token_auth-8a6ba641445e/app/controllers/devise_token_auth/omniauth_callbacks_controller.rb:5`
And I'm still trying to unerstand why this error only appears in production environment, not in development environment.

**Comment by djsegal** [comment]
@jakubrohleder just making sure, you're using rails 5 also, right?

the temporary workaround is just to set `config.eager_load = false`. obviously, this is suboptimal

**Comment by jakubrohleder** [comment]
@djsegal I haven't tested the gem with rails 5. I'll take a look by the end of a week.

**Comment by jeryRazakarison** [comment]
Thank you @jakubrohleder!
In order to reproduce it, just create a new rails 5 project (no need for API mode), and just add the gem, master branch to the Gemfile
`gem 'devise_token_auth', github:"lynndylanhurley/devise_token_auth", branch: "master"``

Then `rails s -e production`raises the error.

(thank you @djsegal for the `eager_load` workaround ;) )

**Comment by djsegal** [comment]
I'm guessing something needs to get autoloaded. I just don't completely understand eager loading at the moment

**Comment by jeryRazakarison** [comment]
ok, this is because now, in Rails 5,
`ActiveSupport::Callbacks#skip_callback` now raises an `ArgumentError` if an unrecognized callback is removed. (https://github.com/rails/rails/blob/v5.0.0.beta1/activesupport/CHANGELOG.md)

You can see the diff for skip_callback here: 
Rails 4 will ignore the unrecognized callback
https://github.com/rails/rails/blob/489a8f2a44dc9cea09154ee1ee2557d1f037c7d4/activesupport/lib/active_support/callbacks.rb#L626

Rails 5 will raise the exception https://github.com/rails/rails/blob/6dfab475ca230dfcad7a603483431c8e7a8f908e/activesupport/lib/active_support/callbacks.rb#L634

A solution is then to add the option `raise: false`, to the `skip_before_action :set_user_by_token`

I know this is not a pretty solution, but it replicate Rails 4 behavior.

**Comment by jeryRazakarison** [comment]
The corresponding PR is here #511

**Comment by booleanbetrayal** [comment]
should be working via #511. thanks all!

**Comment by v3rron** [comment]
This PR didn't make it to 0.1.37 version?
Just installed the latest gem version and this issue still exist :(

**Comment by jeryRazakarison** [comment]
Hi @v3rron , you have to use the latest github version of this gem, like this in your Gemfile
`gem 'devise_token_auth', github:"lynndylanhurley/devise_token_auth", branch: "master"`
then `bundle`and `rails s -e production`to test and it should be good.

(For now, just using `gem 'devise_token_auth'`still do the error.)

Can you confirm?

**Comment by v3rron** [comment]
Yeah, that's what I exactly ended up doing. It works now. Thanks

**Comment by williamweckl** [comment]
This has already been done a long time ago, any plans to launch the next version so that we dont need to get from the master branch?
